---
driver:
  name: vagrant

provisioner:
  name: chef_zero
verifier:
  name: inspec

platforms:
  - name: a_centos_type
  - name: a_windows_type
#  - name: ubuntu-20040-x64
#    driver:
#      box: ubuntu-20040-x64
#      box_url: http://atlas.tripwirelab.com:8080/vagrant/ubuntu-20040-x64
#      provider: vsphere
  - name: oracle-79uek-x64
    driver:
      box: oracle-79uek-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/oracle-79uek-x64
      provider: vsphere
  - name: oracle-85uek-x64
    driver:
      box: oracle-85uek-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/oracle-85uek-x64
      provider: vsphere
  - name: amazon-2-x64
    driver:
      box: amazon-2-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/amazon-2-x64
      provider: vsphere
  - name: suse-15sp0-x64
    driver:
      box: suse-15sp0-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/suse-15sp0-x64
      provider: vsphere
  - name: suse-15sp1-x64
    driver:
      box: suse-15sp1-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/suse-15sp1-x64
      provider: vsphere
  - name: suse-12sp5-x64
    driver:
      box: suse-12sp5-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/suse-12sp5-x64
      provider: vsphere
  - name: redhat-80-x64
    driver:
      box: redhat-80-x64
      box_url: http://atlas.tripwirelab.com:8080/vagrant/redhat-80-x64
      provider: vsphere


suites:
# Tests basic installation of the java agent for linux
  - name: java-lnx-basic
    run_list:
      - recipe[tripwire_agent::java_agent]
    verifier:
      inspec_tests:
        - test/smoke/java-basic
    excludes:
      - a_windows_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.bin'
        tags: { "tag_set1": [ "1_tag1", "1_tag2" ], "tag_set2": "2_tag1" }
        java:
          console: 'testconsole.example.com'
          services_password: 'P@s5w0rd!C0mp13XP@s5w0rD!'

  - name: java-lnx-comp
    run_list:
      - recipe[tripwire_agent::java_agent]
    verifier:
      inspec_tests:
        - test/smoke/java-comprehensive
    excludes:
      - a_windows_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.bin'
        proxy_hostname: 'tw-proxy.example.com'
        proxy_port: 1560
        rtm_port: 1269
        start_service: false
        java:
          console: 'testconsole.example.com'
          console_port: 6565
          services_password: 'services'
          install_directory: '/opt/tripwire/te/agent'
          proxy_agent: true

  - name: java-lnx-remove
    run_list:
      - recipe[tripwire_agent::java_agent]
      - recipe[tripwire_agent::java_remove]
    verifier:
      inspec_tests:
        - test/smoke/java-remove
    excludes:
      - a_debian_type
      - a_windows_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.bin'
        tags: { "tag_set1": [ "1_tag1", "1_tag2" ], "tag_set2": "2_tag1" }
        java:
          console: 'testconsole.example.com'
          services_password: 'P@s5w0rd!C0mp13XP@s5w0rD!'

# Tests basic installation of the java agent for debian
  - name: java-deb-basic
    run_list:
      - recipe[tripwire_agent::java_agent]
    verififer:
      inspec_tests:
        - test/smoke/java-basic
    excludes:
      - a_windows_type
      - a_centos_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.bin'
        tags: { "tag_set1": [ "1_tag1", "1_tag2" ], "tag_set2": "2_tag1" }
        java:
          console: 'testconsole.example.com'
          services_password: 'P@s5w0rd!C0mp13XP@s5w0rD!'

  - name: java-deb-comp
    run_list:
      - recipe[tripwire_agent::java_agent]
    verifier:
      inspec_tests:
        - test/smoke/java-deb-comprehensive
    excludes:
      - a_centos_type
      - a_windows_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.bin'
        proxy_hostname: 'tw-proxy.example.com'
        proxy_port: 1560
        rtm_port: 1269
        start_service: false
        java:
          console: 'testconsole.example.com'
          console_port: 6565
          services_password: 'services'
# Cannot use custom installation directories on Debian platforms
#          install_directory: '/opt/tripwire/te/agent'
          proxy_agent: true

  - name: java-deb-remove
    run_list:
      - recipe[tripwire_agent::java_agent]
      - recipe[tripwire_agent::java_remove]
    verifier:
      inspec_tests:
        - test/smoke/java-remove
    excludes:
      - a_windows_type
      - a_centos_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.bin'
        tags: { "tag_set1": [ "1_tag1", "1_tag2" ], "tag_set2": "2_tag1" }
        java:
          console: 'testconsole.example.com'
          services_password: 'P@s5w0rd!C0mp13XP@s5w0rD!'

# Tests basic installation of the java agent for windows
  - name: java-win-basic
    run_list:
      - recipe[tripwire_agent::java_agent]
    verifier:
        inspec_tests:
          - test/smoke/java-basic
    excludes:
      - a_centos_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.msi'
        tags: { "tag_set1": [ "1_tag1", "1_tag2" ], "tag_set2": "2_tag1" }
        java:
          console: 'testconsole.example.com'
          services_password: 'P@s5w0rd!C0mp13XP@s5w0rD!'

  - name: java-win-comp
    run_list:
      - recipe[tripwire_agent::java_agent]
    verifier:
      inspec_tests:
        - test/smoke/java-comprehensive
    excludes:
      - a_centos_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.msi'
        proxy_hostname: 'tw-proxy.example.com'
        proxy_port: 1560
        rtm_port: 1269
        start_service: false
        java:
          console: 'testconsole.example.com'
          console_port: 6565
          services_password: 'services'
          install_directory: 'C:\Tripwire\TE\agent'
          proxy_agent: true

  - name: java-win-remove
    run_list:
      - recipe[tripwire_agent::java_agent]
      - recipe[tripwire_agent::java_remove]
    verifier:
        inspec_tests:
          - test/smoke/java-remove
    excludes:
      - a_centos_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/te_agent.msi'
        tags: { "tag_set1": [ "1_tag1", "1_tag2" ], "tag_set2": "2_tag1" }
        java:
          console: 'testconsole.example.com'
          services_password: 'P@s5w0rd!C0mp13XP@s5w0rD!'

##########
# Axon Tests

  - name: axon-lnx-basic
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-basic
    excludes:
      - a_windows_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.rpm'
        axon:
          eg_driver_installer: '/path/to/tw-eg-driver-rhel-1.3.313-1.x86_64.rpm'
          eg_service_installer: '/path/to/tw-eg-service-1.3.326-1.x86_64.rpm'
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }

# TODO remove, OL, amazon linux
  - name: axon-lnx-basic-OLuek-eg-p1
    run_list:
      - recipe[tripwire_agent::axon_agent]
    #    verifier:
    #      inspec_tests:
    #        - test/smoke/axon-noeg
    includes:
      - oracle-79uek-x64
    attributes:
      tripwire_agent:
        installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_linux_x86_64.tgz'
        axon:
          bridge: '10.252.104.103'
          eg_install: true
          use_dkms_driver: true

  - name: axon-lnx-basic-OLuek85-eg-p1
    run_list:
      - recipe[tripwire_agent::axon_agent]
    #    verifier:
    #      inspec_tests:
    #        - test/smoke/axon-noeg
    includes:
      - oracle-85uek-x64
    attributes:
      tripwire_agent:
        installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_linux_x86_64.tgz'
        axon:
          bridge: '10.252.104.103'
          eg_install: true
          use_dkms_driver: true

  - name: axon-lnx-basic-amazon-eg-p1
    run_list:
      #- recipe[tripwire_agent::axon_agent]
      - recipe[tripwire_agent::suse]
    #    verifier:
    #      inspec_tests:
    #        - test/smoke/axon-noeg
    includes:
      - amazon-2-x64
    attributes:
      tripwire_agent:
        installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_linux_x86_64.tgz'
        axon:
          bridge: '10.252.104.103'
          eg_install: true
          use_dkms_driver: true

  - name: axon-lnx-basic-rhel-eg-p1
    run_list:
      - recipe[tripwire_agent::axon_agent]
    #    verifier:
    #      inspec_tests:
    #        - test/smoke/axon-noeg
    includes:
      - redhat-80-x64
    attributes:
      tripwire_agent:
        installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_linux_x86_64.tgz'
        axon:
          bridge: '10.252.104.103'
          eg_install: true
#          use_dkms_driver: true

  - name: axon-lnx-basic-suse15-eg-p1
    run_list:
      - recipe[tripwire_agent::axon_agent]
      #- recipe[tripwire_agent::suse]
    #    verifier:
    #      inspec_tests:
    #        - test/smoke/axon-noeg
    includes:
      - suse-15sp1-x64
      - suse-15sp0-x64
      - suse-12sp5-x64
    attributes:
      tripwire_agent:
        installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_linux_x86_64.tgz'
        axon:
          bridge: '10.252.104.103'
          eg_install: true

  - name: ip360-lnx-basic
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-ip360
    excludes:
      - win2k12r2
      - debian9
      - ubuntu1604
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.rpm'
        axon:
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
          install_directory: '/opt/tripwire/agent-ip360'
          config_directory: '/etc/tripwire-ip360'
          service_name: 'tw-axon-agent-ip360'

  - name: axon-lnx-noeg
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-noeg
    excludes:
      - a_windows_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.rpm'
        axon:
          eg_install: false
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }

  - name: axon-lnx-comp
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-comprehensive
    excludes:
      - a_windows_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.rpm'
        proxy_hostname: 'tw-proxy.example.com'
        proxy_port: 1180
        start_service: false
        axon:
          eg_install: false
          enable_dns: true
          dns_srvc_name: 'bridge'
          dns_srvc_domain: 'example.com'
          proxy_username: 'twsocks01'
          proxy_password: 'T357pAs5W0rD!'
          spool_size: '3g'
          tls_version: 'TLSv1.1'
          cipher_suites: 'AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384'

  - name: axon-lnx-remove
    run_list:
      - recipe[tripwire_agent::axon_agent]
      - recipe[tripwire_agent::axon_remove]
    verifier:
      inspec_tests:
        - test/smoke/axon-remove
    excludes:
      - a_windows_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.rpm'
        axon:
          eg_driver_installer: '/path/to/tw-eg-driver-rhel-1.3.313-1.x86_64.rpm'
          eg_service_installer: '/path/to/tw-eg-service-1.3.326-1.x86_64.rpm'
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }


  - name: axon-deb-basic
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-basic
    excludes:
      - a_windows_type
      - a_centos_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.deb'
        axon:
          eg_driver_installer: '/path/to/tw-eg-driver-debian-1.3.313-1-x64.deb'
          eg_service_installer: '/path/to/tw-eg-service-1.3.326-1-x64.deb'
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }

  - name: ip360-deb-basic
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-ip360
    excludes:
      - a_windows_type
      - a_centos_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.deb'
        axon:
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
          install_directory: '/opt/tripwire/agent-ip360'
          config_directory: '/etc/tripwire-ip360'
          service_name: 'tw-axon-agent-ip360'

  - name: axon-deb-noeg
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-noeg
    excludes:
      - a_windows_type
      - a_centos_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.deb'
        axon:
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
          eg_install: false
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }

# TODO remove
#  - name: axon-ubu-eg-p1
#    run_list:
#      - recipe[tripwire_agent::axon_agent]
##    verifier:
##      inspec_tests:
##        - test/smoke/axon-noeg
#    excludes:
#      - a_windows_type
#      - a_centos_type
#    attributes:
#      tripwire_agent:
#        installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_debian_x86_64.tgz'
#        axon:
#          bridge: '10.252.104.103'
##          registration_key: '123PAs5W0rD'
#          eg_install: true
#          use_dkms_driver: true
##        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }
#
#  - name: axon-ubu-eg-p2
#      run_list:
#        - recipe[tripwire_agent::axon_agent]
#      #    verifier:
#      #      inspec_tests:
#      #        - test/smoke/axon-noeg
#      excludes:
#        - a_windows_type
#        - a_centos_type
#      attributes:
#        tripwire_agent:
#          installer: 'http://downloads.perf.lab.tripwire.com/static/builds/te-axon-bundle/8.8.3.7/8.8.3.7/latest/release/rtw/axon-agent/8.8.3.7/installers/axon_agent_te_8.8.3.7_en_debian_x86_64.tgz'
#          axon:
#            bridge: '10.252.104.103'
#            eg_install: true
#            use_dkms_driver: false

  - name: axon-deb-comp
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-comprehensive
    excludes:
      - a_centos_type
      - a_windows_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.deb'
        proxy_hostname: 'tw-proxy.example.com'
        proxy_port: 1180
        start_service: false
        axon:
          eg_install: false
          enable_dns: true
          dns_srvc_name: 'bridge'
          dns_srvc_domain: 'example.com'
          proxy_username: 'twsocks01'
          proxy_password: 'T357pAs5W0rD!'
          spool_size: '3g'
          tls_version: 'TLSv1.1'
          cipher_suites: 'AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384'

  - name: axon-deb-remove
    run_list:
      - recipe[tripwire_agent::axon_agent]
      - recipe[tripwire_agent::axon_remove]
    verifier:
      inspec_tests:
        - test/smoke/axon-remove
    excludes:
      - a_centos_type
      - a_windows_type
    attributes:
      tripwire_agent:
        installer: '/path/to/axon-agent-installer-linux-x64.deb'
        axon:
          eg_driver_installer: '/path/to/tw-eg-driver-debian-1.3.313-1-x64.deb'
          eg_service_installer: '/path/to/tw-eg-service-1.3.326-1-x64.deb'
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }

  - name: axon-win-basic
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-basic
    excludes:
      - a_centos_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: 'D:\Path\To\Axon_Agent_x64.msi'
        axon:
          bridge: 'tw-bridge.example.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }

  - name: axon-win-comp
    run_list:
      - recipe[tripwire_agent::axon_agent]
    verifier:
      inspec_tests:
        - test/smoke/axon-comprehensive
    excludes:
      - a_centos_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: 'D:\Path\To\Axon_Agent_x64.msi'
        proxy_hostname: 'tw-proxy.example.com'
        proxy_port: 1180
        start_service: false
        axon:
          eg_install: false
          enable_dns: true
          dns_srvc_name: 'bridge'
          dns_srvc_domain: 'example.com'
          proxy_username: 'twsocks01'
          proxy_password: 'T357pAs5W0rD!'
          spool_size: '3g'
          tls_version: 'TLSv1.1'
          cipher_suites: 'AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384'

  - name: axon-win-remove
    run_list:
      - recipe[tripwire_agent::axon_agent]
      - recipe[tripwire_agent::axon_remove]
    verifier:
      inspec_tests:
        - test/smoke/axon-remove
    excludes:
      - a_centos_type
      - a_debian_type
    attributes:
      tripwire_agent:
        installer: 'D:\Path\To\Axon_Agent_x64.msi'
        axon:
          bridge: 'tw-bridge.perf.tripwire.com'
          registration_key: '123PAs5W0rD'
        tags: { 'tagset1': 'tag1a' , 'tagset2': [ 'tag2a', 'tag2b' ],'tagset3': [ 'tag3a', 'tag3b', 'tag3c' ] }
